// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mvc3.Extensions.Demo.Areas.CascadingDropDownLists.Controllers {
    public partial class DropDownjQueryAjaxPostController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DropDownjQueryAjaxPostController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetCountries() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetCountries);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetCities() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetCities);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DropDownjQueryAjaxPostController Actions { get { return MVC.CascadingDropDownLists.DropDownjQueryAjaxPost; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CascadingDropDownLists";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "DropDownjQueryAjaxPost";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string jQueryTemplates = "jQueryTemplates";
            public readonly string KnockOutJs = "KnockOutJs";
            public readonly string CascadePlugin = "CascadePlugin";
            public readonly string GetContinents = "GetContinents";
            public readonly string GetCountries = "GetCountries";
            public readonly string GetCities = "GetCities";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string CascadePlugin = "~/Areas/CascadingDropDownLists/Views/DropDownjQueryAjaxPost/CascadePlugin.cshtml";
            public readonly string Index = "~/Areas/CascadingDropDownLists/Views/DropDownjQueryAjaxPost/Index.cshtml";
            public readonly string jQueryTemplates = "~/Areas/CascadingDropDownLists/Views/DropDownjQueryAjaxPost/jQueryTemplates.cshtml";
            public readonly string KnockoutJs = "~/Areas/CascadingDropDownLists/Views/DropDownjQueryAjaxPost/KnockoutJs.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_DropDownjQueryAjaxPostController: Mvc3.Extensions.Demo.Areas.CascadingDropDownLists.Controllers.DropDownjQueryAjaxPostController {
        public T4MVC_DropDownjQueryAjaxPostController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ViewResult Index() {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ViewResult jQueryTemplates() {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.jQueryTemplates);
            return callInfo;
        }

        public override System.Web.Mvc.ViewResult KnockOutJs() {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.KnockOutJs);
            return callInfo;
        }

        public override System.Web.Mvc.ViewResult CascadePlugin() {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.CascadePlugin);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetContinents() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetContinents);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetCountries(int continentId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetCountries);
            callInfo.RouteValueDictionary.Add("continentId", continentId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetCities(int countryId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetCities);
            callInfo.RouteValueDictionary.Add("countryId", countryId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
