// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mvc3.Extensions.Demo.Areas.CascadingDropDownLists.Controllers {
    public partial class DropDownHijaxPostController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DropDownHijaxPostController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SelectContinent() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SelectContinent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SelectCountry() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SelectCountry);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DropDownHijaxPostController Actions { get { return MVC.CascadingDropDownLists.DropDownHijaxPost; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CascadingDropDownLists";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "DropDownHijaxPost";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string SelectContinent = "SelectContinent";
            public readonly string SelectCountry = "SelectCountry";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _Cities = "~/Areas/CascadingDropDownLists/Views/DropDownHijaxPost/_Cities.cshtml";
            public readonly string _Continents = "~/Areas/CascadingDropDownLists/Views/DropDownHijaxPost/_Continents.cshtml";
            public readonly string _Countries = "~/Areas/CascadingDropDownLists/Views/DropDownHijaxPost/_Countries.cshtml";
            public readonly string Index = "~/Areas/CascadingDropDownLists/Views/DropDownHijaxPost/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_DropDownHijaxPostController: Mvc3.Extensions.Demo.Areas.CascadingDropDownLists.Controllers.DropDownHijaxPostController {
        public T4MVC_DropDownHijaxPostController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SelectContinent(int? selectedContinentId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SelectContinent);
            callInfo.RouteValueDictionary.Add("selectedContinentId", selectedContinentId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SelectCountry(int? selectedContinentId, int? selectedCountryId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SelectCountry);
            callInfo.RouteValueDictionary.Add("selectedContinentId", selectedContinentId);
            callInfo.RouteValueDictionary.Add("selectedCountryId", selectedCountryId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
